version: "3.4"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    restart: always
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "mongo:27017"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
