version: "3"
services:
  web:
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - mongodb
    restart: always
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
    - "27017:27017"
