version: "3.4"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    restart: always
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
